services:
  nginx:
    image: nginx:alpine
    container_name: magazyn-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/magazynbystrze.pl.conf:/etc/nginx/conf.d/magazynbystrze.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /usr/share/nginx/html:/usr/share/nginx/html:ro
    networks:
      - magazyn-network
    depends_on:
      - web
  migrate:
    image: migrate/migrate
    command: -path=/migrations -database postgres://postgres:postgres@db:5432/magazyn?sslmode=disable up
    volumes:
      - ./migrations:/migrations
    depends_on:
        - db
    networks:
      - magazyn-network
  web:
    image: bystrze-magazyn-app:${IMAGE_TAG-latest}
    build:
      context: . 
      dockerfile: app-dockerfile  
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/magazyn?sslmode=disable
      - DEBUG=${DEBUG:-True}
      - MAGAZYN_BYSTRZE_EMAIL_ADDR=${MAGAZYN_BYSTRZE_EMAIL_ADDR:-}
      - MAGAZYN_BYSTRZE_EMAIL_PASS=${MAGAZYN_BYSTRZE_EMAIL_PASS:-}
      - COOKIE_KEY=${COOKIE_KEY:-}
      - SERVER=${SERVER:-http://localhost:8080}
    depends_on:
      - db
    networks:
      - magazyn-network
    restart: unless-stopped

  db:
    image: bystrze-magazyn-db:${IMAGE_TAG:-latest}
    build:
      context: . 
      dockerfile: db-dockerfile
    environment:
      POSTGRES_DB: magazyn
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - magazyn-network
    ports:
      - "127.0.0.1:54320:5432"
    volumes:
      - magazyn_pgdata:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  magazyn_pgdata:

networks:
  magazyn-network:
    driver: bridge
