version: "3"
services:
  smtp_server:
    image: greenmail/standalone:1.6.6
    container_name: test_smtp_server
    networks:
    - test_network_no_web
    ports:
    - 3465:3465
    - 8025:8080
    environment:
    - JAVA_OPTS=-Dgreenmail.verbose -Dgreenmail.auth.enabled
    build:
      context: ""
      dockerfile: ""
      args: {}
  test_app:
    image: test_app
    container_name: test_app
    networks:
    - test_network_no_web
    ports:
    - 8080:8080
    environment:
    - SMTP_HOST=test_smtp_server
    - SMTP_PORT=3465
    build:
      context: .
      dockerfile: .
      args:
        EMAIL: test_app@bystrzeMail.com
        EMAIL_PASS: password
networks:
  test_network_no_web: {}
