name: Run box tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - uses: docker/setup-compose-action@v1 
      - name: Build docker images
        run: docker build --target test --build-arg DEBUG=true -t app -f app-dockerfile .
      - name: Setup containers
        working-directory: ./boxTest
        run: go run main.go --env
      - name: Sleep
        run: sleep 60
      - name: Run tests
        working-directory: ./boxTest
        run: go run main.go --tests
      - name: Show db logs if tests falied
        if: failure()
        run: docker container logs boxtest-db-1 
      - name: Save failed tests data
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: failedTests
          path: ./boxTest/failedTests/
